language: generic

branches:
  only:
  - dev


sudo: required
services: docker

install:
 - source texlive.sh

env:
- TEXMFHOME=${TRAVIS_BUILD_DIR}/texmf

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive


script: 
 - l3build check -q -H
